{% set version = "0.2.2" %}

package:
  name: vale-styles-alex
  version: {{ version }}

source:
  - folder: alex
    fn: vale-alex-0.2.1.zip
    url: https://github.com/errata-ai/alex/releases/download/v{{ version }}/alex.zip
    sha256: 7305960bf51f1bacbdf4a76d4dd649994717d2569905fc828bdd808f55509cfa
  - fn: LICENSE-vale-alex-0.2.1
    url: https://raw.githubusercontent.com/errata-ai/alex/v{{ version }}/LICENSE
    sha256: 08fb0509895870677046735e0827597e0ae7fe805e00697a86a93711cbb178a1

build:
  noarch: generic
  number: 0

requirements:
  host:
    - vale
  run:
    - vale

test:
  requires:
    - pytest

about:
  home: https://github.com/errata-ai/alex
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: alex rules for vale grammar and style checker

extra:
  recipe-maintainers:
    - bollwyvl
