{% set version = "0.2.3" %}

package:
  name: vale-styles-alex
  version: {{ version }}

source:
  - folder: alex
    fn: vale-alex-0.2.1.zip
    url: https://github.com/errata-ai/alex/releases/download/v{{ version }}/alex.zip
    sha256: 44014c7f63d4a8bce86788e074edb80333a9b6eba07e5dd27b24823b69eed50b
  - fn: LICENSE-vale-alex-0.2.1
    url: https://raw.githubusercontent.com/errata-ai/alex/v{{ version }}/LICENSE
    sha256: 08fb0509895870677046735e0827597e0ae7fe805e00697a86a93711cbb178a1

build:
  noarch: generic
  number: 0

requirements:
  host:
    - vale
  run:
    - vale

test:
  requires:
    - pytest

about:
  home: https://github.com/errata-ai/alex
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: alex rules for vale grammar and style checker

extra:
  recipe-maintainers:
    - bollwyvl
